### ISSUE TITLE
TLS 1.3 support with openssl11 from EPEL

### ISSUE THREAD

**Issue by prupert** [iusrepo/haproxy20#10]
OpenSSL 1.1 is supported on CentOS 7 through EPEL packages `openssl11`. 

Now that [nginx in EPEL 7 is built against OpenSSL 1.1](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2021-c64b965c33) from EPEL to allow the use of TLSv1.3, we were hoping that you would do the same for HAProxy packages in IUS.

**Comment by carlwgeorge** [comment]
Thanks for opening an issue for this, but I'd prefer to just reopen the old one.  We can work on it there.
